### PR TITLE
Benchmark Script

### PR DESCRIPTION
**Pull request by Garfield96**
Added avg calculation

### CODE REVIEW

**Comment by domargan** [comment]
@Garfield96 It seems that this pull request includes some of the approved commits from previous PR #9. It should include only [83e7a24](https://github.com/domargan/parallel-packed-csr/pull/10/commits/83e7a248c99c6e08c7169e5550e6bb2042027957)?

**Review by domargan — APPROVED** [review]

**Comment by domargan** [comment]
Approving the changes for 83e7a24 but the other commits should be removed as they are already merged with master.

**Comment by domargan** [comment]
@Garfield96 I added the plotting as discussed. The script could be further improved and we will need to introduce more benchmarks into it, but this should do for now.

**Comment by domargan** [comment]
@Garfield96 Please let me know when you are happy to give a green light for merging the pull request so I could do it.

**Comment by Garfield96** [comment]
I tested it and it worked fine

**Pull request merged**
